# Generated by Django 5.1.2 on 2024-10-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('days_of_week', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
